1. Let's normalize ad_events data. I'm going to save data to dataset-normalized folder after each step of modification

In [47]:
import pandas as pd

# Fix file by separating data from TargetingCriteria column (due to unquoted commas)
fixed_rows = []
with open("dataset/ad_events.csv", 'r') as f:
    header = f.readline().strip().split(',')

    for line in f:
        parts = line.strip().split(',')

        # 18 columns + 3 from TargetingCriteria
        if len(parts) >= 20:
            # Recombine TargetingCriteria (assumed to be split into 3 parts at positions 5,6,7)
            fixed = (
                parts[:5] +                                     # EventID to CampaignEndDate
                [','.join(parts[5:8]).strip()] +                # TargetingCriteria (3 parts)
                parts[8:]                                       # Remaining columns
            )

            # Only accept rows that fix to exactly 18 columns
            if len(fixed) == 18:
                fixed_rows.append(fixed)

df = pd.DataFrame(fixed_rows, columns=header)

In [49]:
len(df)

10000000

In [48]:
df.head()

,EventID,AdvertiserName,CampaignName,CampaignStartDate,CampaignEndDate,TargetingCriteria,AdSlotSize,UserID,Device,Location,Timestamp,BidAmount,AdCost,WasClicked,ClickTimestamp,AdRevenue,Budget,RemainingBudget
0,e067dae7-9aaa-4b9c-9195-7af63ce89216,Advertiser_30,Campaign_278,2024-10-10,2024-11-12,"Age 29-46, Gaming, Germany",300x250,289903,Mobile,USA,2024-10-31T06:56:39,4.6,3.7,False,,0.0,279306.6,279306.6
1,ea95edfa-1ba0-444d-a40d-a3f064dd5791,Advertiser_25,Campaign_235,2024-10-24,2024-11-28,"Age 22-33, Gaming, Australia",728x90,145276,Desktop,UK,2024-11-13T09:19:34,3.5,2.85,False,,0.0,88914.6,88914.6
2,5f12c537-ac88-4fcc-8d23-b3fa2b538a3b,Advertiser_95,Campaign_947,2024-10-31,2024-11-11,"Age 27-42, Health, USA",300x250,83608,Desktop,USA,2024-11-08T14:36:14,3.75,3.16,False,,0.0,207892.45,207892.45
3,191d7957-90ec-4e6c-aaec-f70c6ca57513,Advertiser_53,Campaign_530,2024-10-25,2024-11-20,"Age 18-36, Fashion, USA",300x250,280085,Mobile,Australia,2024-11-10T22:39:42,0.83,0.73,False,,0.0,181597.78,181597.78
4,42a66a39-a275-4007-81de-21182d3ead70,Advertiser_5,Campaign_35,2024-10-02,2024-11-26,"Age 30-43, Technology, India",728x90,656312,Mobile,USA,2024-10-17T20:05:20,0.91,0.82,False,,0.0,354525.31,354525.31

In [50]:
df.to_csv("dataset_normalized/ad_events.csv", index=False)

In [51]:
# remove duplicates
df = df.drop_duplicates()

In [52]:
# remove duplicate EventIDs
df = df.drop_duplicates(subset='EventID')

In [53]:
df.to_csv("dataset_normalized/ad_events.csv", index=False)

In [54]:
len(df)

10000000

In [55]:
# fix data types
df['CampaignStartDate'] = pd.to_datetime(df['CampaignStartDate'], errors='coerce')
df['CampaignEndDate'] = pd.to_datetime(df['CampaignEndDate'], errors='coerce')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
df['ClickTimestamp'] = pd.to_datetime(df['ClickTimestamp'], errors='coerce')

In [57]:
df

,EventID,AdvertiserName,CampaignName,CampaignStartDate,CampaignEndDate,TargetingCriteria,AdSlotSize,UserID,Device,Location,Timestamp,BidAmount,AdCost,WasClicked,ClickTimestamp,AdRevenue,Budget,RemainingBudget
0,e067dae7-9aaa-4b9c-9195-7af63ce89216,Advertiser_30,Campaign_278,2024-10-10,2024-11-12,"Age 29-46, Gaming, Germany",300x250,289903,Mobile,USA,2024-10-31 06:56:39,4.6,3.7,False,NaT,0.0,279306.6,279306.6
1,ea95edfa-1ba0-444d-a40d-a3f064dd5791,Advertiser_25,Campaign_235,2024-10-24,2024-11-28,"Age 22-33, Gaming, Australia",728x90,145276,Desktop,UK,2024-11-13 09:19:34,3.5,2.85,False,NaT,0.0,88914.6,88914.6
2,5f12c537-ac88-4fcc-8d23-b3fa2b538a3b,Advertiser_95,Campaign_947,2024-10-31,2024-11-11,"Age 27-42, Health, USA",300x250,83608,Desktop,USA,2024-11-08 14:36:14,3.75,3.16,False,NaT,0.0,207892.45,207892.45
3,191d7957-90ec-4e6c-aaec-f70c6ca57513,Advertiser_53,Campaign_530,2024-10-25,2024-11-20,"Age 18-36, Fashion, USA",300x250,280085,Mobile,Australia,2024-11-10 22:39:42,0.83,0.73,False,NaT,0.0,181597.78,181597.78
4,42a66a39-a275-4007-81de-21182d3ead70,Advertiser_5,Campaign_35,2024-10-02,2024-11-26,"Age 30-43, Technology, India",728x90,656312,Mobile,USA,2024-10-17 20:05:20,0.91,0.82,False,NaT,0.0,354525.31,354525.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999995,7be72c4f-80f2-4ec1-94ae-51d081f73bf5,Advertiser_33,Campaign_306,2024-10-16,2024-11-01,"Age 22-48, Gaming, Germany",728x90,475249,Desktop,India,2024-10-21 10:59:52,2.06,1.63,True,2024-10-21 11:00:13,0.84,275259.9,275259.9
9999996,504aa3a0-d012-48eb-9cf2-d1279eadfcef,Advertiser_66,Campaign_659,2024-10-12,2024-12-05,"Age 22-43, Sports, UK",728x90,314226,Tablet,India,2024-11-03 05:30:48,1.01,0.85,False,NaT,0.0,292330.69,292330.69
9999997,976c169b-f37e-4b3c-9902-6f96f9c82fd0,Advertiser_45,Campaign_433,2024-10-22,2024-12-04,"Age 28-39, Gaming, UK",300x250,222436,Desktop,Australia,2024-11-25 11:49:50,3.94,3.29,False,NaT,0.0,82894.54,82894.54
9999998,600a51fe-9f7e-4cba-8fee-c0ec34b60f78,Advertiser_33,Campaign_310,2024-10-30,2024-12-14,"Age 20-35, Fashion, India",160x600,129395,Desktop,India,2024-11-20 18:26:43,3.06,2.8,False,NaT,0.0,177541.35,177541.35
9999999,3b688e32-beb0-4d4e-b562-50665244a964,Advertiser_83,Campaign_828,2024-10-06,2024-10-29,"Age 29-39, Finance, UK",300x250,654498,Tablet,USA,2024-10-07 13:51:17,0.62,0.56,False,NaT,0.0,250992.46,250992.46

In [105]:
df['AdvertiserName'].nunique()

100

In [106]:
df['CampaignName'].nunique()

1013

In [60]:
df.dtypes

EventID                      object
AdvertiserName               object
CampaignName                 object
CampaignStartDate    datetime64[ns]
CampaignEndDate      datetime64[ns]
TargetingCriteria            object
AdSlotSize                   object
UserID                       object
Device                       object
Location                     object
Timestamp            datetime64[ns]
BidAmount                    object
AdCost                       object
WasClicked                   object
ClickTimestamp       datetime64[ns]
AdRevenue                    object
Budget                       object
RemainingBudget              object
dtype: object

In [62]:
# fix
numeric_cols = ['BidAmount', 'AdCost', 'AdRevenue', 'Budget', 'RemainingBudget']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [70]:
# check if there are negative numbers
len(df[(df['BidAmount'] < 0) | (df['AdCost'] < 0) | (df['AdRevenue'] < 0) | (df['Budget'] < 0) | (df['RemainingBudget'] < 0)])

0

In [71]:
df['WasClicked'] = df['WasClicked'].map({'True': True, 'False': False, True: True, False: False})

In [72]:
df.dtypes

EventID                      object
AdvertiserName               object
CampaignName                 object
CampaignStartDate    datetime64[ns]
CampaignEndDate      datetime64[ns]
TargetingCriteria            object
AdSlotSize                   object
UserID                       object
Device                       object
Location                     object
Timestamp            datetime64[ns]
BidAmount                   float64
AdCost                      float64
WasClicked                     bool
ClickTimestamp       datetime64[ns]
AdRevenue                   float64
Budget                      float64
RemainingBudget             float64
dtype: object

In [75]:
df.isnull().sum()

EventID                    0
AdvertiserName             0
CampaignName               0
CampaignStartDate          0
CampaignEndDate            0
TargetingCriteria          0
AdSlotSize                 0
UserID                     0
Device                     0
Location                   0
Timestamp                  0
BidAmount                  0
AdCost                     0
WasClicked                 0
ClickTimestamp       9500268
AdRevenue                  0
Budget                     0
RemainingBudget            0
dtype: int64

In [78]:
# check if there are invalide rows without ClickTimestamp
invalid_clicks = df[(df['WasClicked'] == True) & (df['ClickTimestamp'].isna())]
len(invalid_clicks)

0

In [79]:
df.to_csv("dataset_normalized/ad_events.csv", index=False)

2. Let's normalize campaigns data

In [83]:
df_campaigns = pd.read_csv('dataset/campaigns.csv')
df_campaigns

,CampaignID,AdvertiserName,CampaignName,CampaignStartDate,CampaignEndDate,TargetingCriteria,AdSlotSize,Budget,RemainingBudget
0,1,Advertiser_1,Campaign_1,2024-10-05,2024-11-16,"Age 24-42, Gaming, India",728x90,183204.20,183204.20
1,2,Advertiser_1,Campaign_2,2024-10-03,2024-11-13,"Age 23-44, Sports, UK",160x600,81431.52,81431.52
2,3,Advertiser_1,Campaign_3,2024-10-18,2024-11-04,"Age 22-34, Finance, Australia",300x250,276829.07,276829.07
3,4,Advertiser_1,Campaign_4,2024-10-04,2024-11-08,"Age 24-45, Health, Germany",300x250,363466.39,363466.39
4,5,Advertiser_1,Campaign_5,2024-10-06,2024-10-29,"Age 19-38, Health, Australia",300x250,468699.97,468699.97
...,...,...,...,...,...,...,...,...,...
1008,1009,Advertiser_100,Campaign_1009,2024-10-27,2024-12-18,"Age 26-45, Education, Australia",160x600,308920.59,308920.59
1009,1010,Advertiser_100,Campaign_1010,2024-10-30,2024-12-24,"Age 18-31, Fashion, India",728x90,150675.26,150675.26
1010,1011,Advertiser_100,Campaign_1011,2024-10-16,2024-11-12,"Age 28-39, Education, UK",160x600,75181.22,75181.22
1011,1012,Advertiser_100,Campaign_1012,2024-10-18,2024-11-19,"Age 30-41, Technology, UK",160x600,277057.39,277057.39
1012,1013,Advertiser_100,Campaign_1013,2024-10-04,2024-11-11,"Age 22-31, Sports, Australia",728x90,27045.56,27045.56

In [84]:
df_campaigns.dtypes

CampaignID             int64
AdvertiserName        object
CampaignName          object
CampaignStartDate     object
CampaignEndDate       object
TargetingCriteria     object
AdSlotSize            object
Budget               float64
RemainingBudget      float64
dtype: object

In [85]:
df_campaigns.isnull().sum()

CampaignID           0
AdvertiserName       0
CampaignName         0
CampaignStartDate    0
CampaignEndDate      0
TargetingCriteria    0
AdSlotSize           0
Budget               0
RemainingBudget      0
dtype: int64

In [92]:
df_campaigns[df_campaigns.duplicated(keep=False)]

Empty DataFrame
Columns: [CampaignID, AdvertiserName, CampaignName, CampaignStartDate, CampaignEndDate, TargetingCriteria, AdSlotSize, Budget, RemainingBudget]
Index: []

In [96]:
# Let's check how many unique Advertisers in the table
df_campaigns['AdvertiserName'].nunique()

100

In [107]:
# Let's check how many unique CampaignName in the table
df_campaigns['CampaignName'].nunique()

1013

In [98]:
df_campaigns['CampaignStartDate'] = pd.to_datetime(df_campaigns['CampaignStartDate'], errors='coerce')
df_campaigns['CampaignEndDate'] = pd.to_datetime(df_campaigns['CampaignEndDate'], errors='coerce')
numeric_cols = ['Budget', 'RemainingBudget']
df_campaigns[numeric_cols] = df_campaigns[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [104]:
# check if there are negative numbers
len(df_campaigns[(df_campaigns['Budget'] < 0) | (df_campaigns['RemainingBudget'] < 0)])

0

In [111]:
df_campaigns.to_csv("dataset_normalized/campaigns.csv", index=False)

3. Let's normalize users dataset

In [112]:
df_users = pd.read_csv('dataset/users.csv')
df_users

,UserID,Age,Gender,Location,Interests,SignupDate
0,1,58,Male,USA,"Gaming,Sports,Health",2020-07-28
1,2,61,Male,Australia,"Technology,Education,Health,Sports",2021-04-21
2,3,50,Male,Australia,"Health,Sports",2022-07-08
3,4,55,Female,USA,"Health,Fashion",2021-07-23
4,5,27,Male,Germany,Sports,2022-02-17
...,...,...,...,...,...,...
699995,699996,63,Male,Germany,"Fashion,Sports",2022-10-17
699996,699997,21,Male,Germany,"Education,Technology,Finance,Health",2020-12-18
699997,699998,55,Female,Australia,"Travel,Gaming",2021-06-12
699998,699999,24,Female,UK,"Health,Travel,Education",2023-02-24
699999,700000,54,Male,USA,Finance,2020-10-21

In [113]:
df_users.dtypes

UserID         int64
Age            int64
Gender        object
Location      object
Interests     object
SignupDate    object
dtype: object

In [114]:
df_users.isnull().sum()

UserID        0
Age           0
Gender        0
Location      0
Interests     0
SignupDate    0
dtype: int64

In [116]:
df_users[df_users.duplicated(keep=False)]

Empty DataFrame
Columns: [UserID, Age, Gender, Location, Interests, SignupDate]
Index: []

In [117]:
# Let's check how many unique Gender in the table
df_users['Gender'].nunique()

2

In [118]:
# Let's check how many unique UserID in the table
df_users['UserID'].nunique()

700000

In [119]:
df_users['SignupDate'] = pd.to_datetime(df_users['SignupDate'], errors='coerce')

In [120]:
# check if there are negative age
len(df_users[(df_users['Age'] <= 0)])

0

In [121]:
df_users.to_csv("dataset_normalized/users.csv", index=False)